version: '3'
services:
  database:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - net

  app:
    build: .
    image: chat-kuepa
    restart: always
    depends_on:
      - database
    ports:
      - '8080:8080'
    networks:
      - net

networks:
  net:
    external: false
