version: '2.1'
services:
  app:
    build: .
    image: chat-kuepa
    depends_on:
      - database
    ports:
      - '8080:8080'
    networks:
      - chat_kuepa_net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://database:27017']
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - chat_kuepa_net

networks:
  chat_kuepa_net:
    external: false
